#!/bin/sh
clear
echo "Autor: Dominik Wiśniewski s396455"
echo "Korektora niechlujnej polszczyzny."
echo "Uwzględniane są 3 rodzaje błędów: ortograficzne(u/ó, ż/rz, h/ch), brak wielkiej lub małej litery i brak znaków diakrytycznych."
echo "Liczymy najtańszy koszt przekształcenia zadanego ciągu znaków."
echo "Słownik: 2mln słów."

echo "Przygotowanie do kompilacji"
read -p "Naciśnij dowolny przycisk aby kontynuować..." continue

#head -n 2000000 Lexicon/polimorfNorm.txt > lex_words.txt
thraxmakedep corrector.grm
make
thraxrewrite-tester --far=corrector.far --rules=corrector

