#!/bin/bash

echo 'Wykonał: Dominik Wiśniewski 396455'
echo 'Zadanie za: 3-4pkt'
echo 'Press any ENTER to continue'
read a

echo 'Zadanie polega na wyciągnięciu z wikipedi konkretnych informacji'
echo 'W tym wypadku są to informacje o noblistach'
echo 'Program potrzebuje imienia bądz nazwiska noblisty i jakiegoś słowa kluczowego'
echo 'Press any ENTER to continue'
read a

echo 'Przykład działania dla słów: Curie i Born'
echo './App.rb Curie Born'
echo 'Press any ENTER to continue'
read a

ruby App.rb Curie Born
echo 'Uzyskaliśmy informacje o urodzeniu noblistów o nazwisku Curie'
echo 'Press any ENTER to continue'
read a

echo 'Przykład działania dla słów: Einstein i Died'
echo './App.rb Einstein Died'
echo 'Press any ENTER to continue'
read a

ruby App.rb Einstein Died
echo 'Uzyskaliśmy informacje o śmierci Einsteina'
echo 'Press any ENTER to continue'
read a

echo 'Instrukcja ogólna: ./App.rb [imie/nazwisko] [słowo_kluczowe]'
echo 'Oba parametry muszą być podane'
echo 'Press any ENTER to continue'
read a
